global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'node'
    ec2_sd_configs:
      - region: us-east-2
        access_key: AKIAXIIBBIEF6QX5RFRL
        secret_key: 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
        port: 9100
